language: node_js
node_js: 
  - "10.13.0"
cache:
  directories:
    - "server/node_modules"
services:
  - mongodb
env:
  - NODE_ENV=travisci
before_install:
  - cd server
  - npm cache clean --force
  - npm install
script:
  - npm test
