language: node_js
node_js:
  - "10.13.0"
cache:
  directories:
  - "node_modules"
services:
  - mongodb
env:
    - NODE_ENV=travisci
before_script:
  - npm cache clean --force
  - npm install
  - cd ..
  - docker-compose build
  - docker-compose up -d
script:
  - npm start

